touch ./BeFS/.ignore
touch ./BeFS/docs/.ignore
touch ./BeFS/source/.ignore
touch ./BeFS/test/.ignore
touch ./app_kit/.ignore
touch ./app_kit/docs/.ignore
touch ./app_kit/source/.ignore
touch ./app_kit/source/lib/.ignore
touch ./app_kit/source/server/.ignore
touch ./app_kit/test/.ignore
touch ./game_kit/.ignore
touch ./game_kit/docs/.ignore
touch ./game_kit/source/.ignore
touch ./game_kit/source/lib/.ignore
touch ./game_kit/source/server/.ignore
touch ./game_kit/test/.ignore
touch ./input_kit/.ignore
touch ./input_kit/docs/.ignore
touch ./input_kit/source/.ignore
touch ./input_kit/source/lib/.ignore
touch ./input_kit/source/server/.ignore
touch ./input_kit/test/.ignore
touch ./kernel_kit/.ignore
touch ./kernel_kit/docs/.ignore
touch ./kernel_kit/source/.ignore
touch ./kernel_kit/source/lib/.ignore
touch ./kernel_kit/source/server/.ignore
touch ./kernel_kit/source/server/boot/.ignore
touch ./kernel_kit/source/server/boot/alpha/.ignore
touch ./kernel_kit/source/server/boot/i386/.ignore
touch ./kernel_kit/source/server/boot/mips/.ignore
touch ./kernel_kit/source/server/boot/ppc/.ignore
touch ./kernel_kit/source/server/boot/sh4/.ignore
touch ./kernel_kit/source/server/boot/sparc/.ignore
touch ./kernel_kit/source/server/boot/sparc/include/.ignore
touch ./kernel_kit/source/server/boot/sparc/include/libkern/.ignore
touch ./kernel_kit/source/server/boot/sparc/include/machine/.ignore
touch ./kernel_kit/source/server/boot/sparc/include/sparc/.ignore
touch ./kernel_kit/source/server/boot/sparc/include/sys/.ignore
touch ./kernel_kit/source/server/boot/sparc/libkern/.ignore
touch ./kernel_kit/source/server/boot/sparc/libsa/.ignore
touch ./kernel_kit/source/server/boot/sparc64/.ignore
touch ./kernel_kit/source/server/bus/.ignore
touch ./kernel_kit/source/server/bus/pci/.ignore
touch ./kernel_kit/source/server/dev/.ignore
touch ./kernel_kit/source/server/dev/arch/.ignore
touch ./kernel_kit/source/server/dev/arch/alpha/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/console/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/ide/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/keyboard/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/pci/.ignore
touch ./kernel_kit/source/server/dev/arch/i386/rtl8139/.ignore
touch ./kernel_kit/source/server/dev/arch/mips/.ignore
touch ./kernel_kit/source/server/dev/arch/ppc/.ignore
touch ./kernel_kit/source/server/dev/arch/sh4/.ignore
touch ./kernel_kit/source/server/dev/arch/sh4/console/.ignore
touch ./kernel_kit/source/server/dev/arch/sh4/maple/.ignore
touch ./kernel_kit/source/server/dev/arch/sh4/rtl8139/.ignore
touch ./kernel_kit/source/server/dev/arch/sparc/.ignore
touch ./kernel_kit/source/server/dev/arch/sparc64/.ignore
touch ./kernel_kit/source/server/dev/common/.ignore
touch ./kernel_kit/source/server/include/.ignore
touch ./kernel_kit/source/server/include/arch/.ignore
touch ./kernel_kit/source/server/include/arch/alpha/.ignore
touch ./kernel_kit/source/server/include/arch/i386/.ignore
touch ./kernel_kit/source/server/include/arch/mips/.ignore
touch ./kernel_kit/source/server/include/arch/ppc/.ignore
touch ./kernel_kit/source/server/include/arch/sh4/.ignore
touch ./kernel_kit/source/server/include/arch/sparc/.ignore
touch ./kernel_kit/source/server/include/arch/sparc64/.ignore
touch ./kernel_kit/source/server/include/boot/.ignore
touch ./kernel_kit/source/server/include/boot/arch/.ignore
touch ./kernel_kit/source/server/include/boot/arch/i386/.ignore
touch ./kernel_kit/source/server/include/boot/arch/mips/.ignore
touch ./kernel_kit/source/server/include/boot/arch/ppc/.ignore
touch ./kernel_kit/source/server/include/boot/arch/sh4/.ignore
touch ./kernel_kit/source/server/include/boot/arch/sparc64/.ignore
touch ./kernel_kit/source/server/include/bus/.ignore
touch ./kernel_kit/source/server/include/bus/pci/.ignore
touch ./kernel_kit/source/server/include/dev/.ignore
touch ./kernel_kit/source/server/include/dev/arch/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/console/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/ide/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/keyboard/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/pci/.ignore
touch ./kernel_kit/source/server/include/dev/arch/i386/rtl8139/.ignore
touch ./kernel_kit/source/server/include/dev/arch/sh4/.ignore
touch ./kernel_kit/source/server/include/dev/arch/sh4/console/.ignore
touch ./kernel_kit/source/server/include/dev/arch/sh4/maple/.ignore
touch ./kernel_kit/source/server/include/dev/arch/sh4/rtl8139/.ignore
touch ./kernel_kit/source/server/include/dev/common/.ignore
touch ./kernel_kit/source/server/include/kernel/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/alpha/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/i386/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/mips/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/ppc/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/sh4/.ignore
touch ./kernel_kit/source/server/include/kernel/arch/sparc64/.ignore
touch ./kernel_kit/source/server/include/kernel/fs/.ignore
touch ./kernel_kit/source/server/include/kernel/net/.ignore
touch ./kernel_kit/source/server/include/libc/.ignore
touch ./kernel_kit/source/server/include/libsys/.ignore
touch ./kernel_kit/source/server/include/sys/.ignore
touch ./kernel_kit/source/server/kernel/.ignore
touch ./kernel_kit/source/server/kernel/arch/.ignore
touch ./kernel_kit/source/server/kernel/arch/i386/.ignore
touch ./kernel_kit/source/server/kernel/arch/mips/.ignore
touch ./kernel_kit/source/server/kernel/arch/ppc/.ignore
touch ./kernel_kit/source/server/kernel/arch/sh4/.ignore
touch ./kernel_kit/source/server/kernel/arch/sparc/.ignore
touch ./kernel_kit/source/server/kernel/arch/sparc64/.ignore
touch ./kernel_kit/source/server/kernel/fs/.ignore
touch ./kernel_kit/source/server/kernel/net/.ignore
touch ./kernel_kit/source/server/kernel/vm/.ignore
touch ./kernel_kit/source/server/lib/.ignore
touch ./kernel_kit/source/server/lib/glue/.ignore
touch ./kernel_kit/source/server/lib/libc/.ignore
touch ./kernel_kit/source/server/lib/libgcc/.ignore
touch ./kernel_kit/source/server/lib/libgcc/alpha/.ignore
touch ./kernel_kit/source/server/lib/libgcc/i386/.ignore
touch ./kernel_kit/source/server/lib/libgcc/mips/.ignore
touch ./kernel_kit/source/server/lib/libgcc/ppc/.ignore
touch ./kernel_kit/source/server/lib/libgcc/sh4/.ignore
touch ./kernel_kit/source/server/lib/libgcc/sh4/ml/.ignore
touch ./kernel_kit/source/server/lib/libgcc/sh4/ml/m4-single-only/.ignore
touch ./kernel_kit/source/server/lib/libsys/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/i386/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/mips/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/ppc/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/sh4/.ignore
touch ./kernel_kit/source/server/lib/libsys/arch/sparc64/.ignore
touch ./kernel_kit/source/server/newos/.ignore
touch ./kernel_kit/source/server/tools/.ignore
touch ./kernel_kit/source/server/tools/sparcbootblock/.ignore
touch ./kernel_kit/test/.ignore
touch ./media_kit/.ignore
touch ./media_kit/docs/.ignore
touch ./media_kit/source/.ignore
touch ./media_kit/source/lib/.ignore
touch ./media_kit/source/server/.ignore
touch ./media_kit/test/.ignore
touch ./net_kit/.ignore
touch ./net_kit/docs/.ignore
touch ./net_kit/source/.ignore
touch ./net_kit/source/lib/.ignore
touch ./net_kit/source/server/.ignore
touch ./net_kit/test/.ignore
touch ./openBeBook/.ignore
touch ./print_kit/.ignore
touch ./print_kit/docs/.ignore
touch ./print_kit/source/.ignore
touch ./print_kit/source/lib/.ignore
touch ./print_kit/source/server/.ignore
touch ./print_kit/test/.ignore
touch ./screensaver_kit/.ignore
touch ./screensaver_kit/docs/.ignore
touch ./screensaver_kit/source/.ignore
touch ./screensaver_kit/source/lib/.ignore
touch ./screensaver_kit/source/server/.ignore
touch ./screensaver_kit/test/.ignore
touch ./storage_kit/.ignore
touch ./storage_kit/docs/.ignore
touch ./storage_kit/source/.ignore
touch ./storage_kit/source/lib/.ignore
touch ./storage_kit/source/server/.ignore
touch ./storage_kit/test/.ignore
