all:
	cd lib/support/BLocker; make
	cd lib/application/BMessageQueue; make

clean:
	cd lib/support/BLocker; make clean
	cd lib/application/BMessageQueue; make clean

runtests:
	cd lib/support/BLocker; make runtests
	cd lib/applicaiton/BMessageQueue; make runtests
