#ifndef MEDIASERVERDEFS
#define MEDIASERVERDEFS




#define NEW_MEDIA_SERVER_SIGNATURE 	"application/x-vnd.MO-new-media-server"
#define MEDIA_SERVER_PRIORITY      	20
#define MEDIA_SERVER_SETTINGS_FILE 	"open_beos_media_server.config"

#define RULE_SETTING_MASTERVOLUME  	"MasterVolume:[01].[0123456789][0123456789][0123456789]*"








//The next definition is that of possible IPC messages that are used when==============
//communicating with the media server.
enum MediaServerMessage_Type {
								MEDIA_SERVER_GET_NODE_ID = 98765,
								MEDIA_SERVER_FIND_RUNNING_INSTANCES,
								MEDIA_SERVER_BUFFER_GROUP_REG,
								MEDIA_SERVER_GET_LATENT_INFO,
								MEDIA_SERVER_GET_DORMANT_FILE_FORMATS,
								MEDIA_SERVER_GET_GETDORMANTFLAVOR,
								MEDIA_SERVER_BROADCAST_MESSAGE,
								MEDIA_SERVER_RELEASE_NODE_REFERENCE,
								MEDIA_SERVER_SET_REALTIME_FLAGS,
								MEDIA_SERVER_GET_REALTIME_FLAGS,
								MEDIA_SERVER_INSTANTIATE_PERSISTENT_NODE,
								MEDIA_SERVER_SNIFF_FILE,
								MEDIA_SERVER_QUERY_LATENTS,
								MEDIA_SERVER_REGISTER_APP,
								MEDIA_SERVER_UNREGISTER_APP,
								MEDIA_SERVER_REGISTER_NODE,
								MEDIA_SERVER_UNREGISTER_NODE,
								MEDIA_SERVER_REGISTER_BUFFER,
								MEDIA_SERVER_SET_DEFAULT,
								MEDIA_SERVER_ACQUIRE_NODE_REFERENCE,
								MEDIA_SERVER_REQUEST_NOTIFICATIONS,
								MEDIA_SERVER_CANCEL_NOTIFICATIONS,
								MEDIA_SERVER_SET_OUTPUT_BUFFERS,
								MEDIA_SERVER_RECLAIM_OUTPUT_BUFFERS,
								MEDIA_SERVER_ORPHAN_RECLAIMABLE_BUFFERS,
								MEDIA_SERVER_SET_TIME_SOURCE,
								MEDIA_SERVER_QUERY_NODES,
								MEDIA_SERVER_GET_DORMANT_NODE,
								MEDIA_SERVER_FORMAT_CHANGED,
								MEDIA_SERVER_GET_DEFAULT_INFO,
								MEDIA_SERVER_GET_RUNNING_DEFAULT,
								MEDIA_SERVER_SET_RUNNING_DEFAULT,
								MEDIA_SERVER_TYPE_ITEM_OP,
								MEDIA_SERVER_FORMAT_OP,
								MEDIA_SERVER_HAS_STARTED,
								MEDIA_SERVER_HAS_DIED,
								MEDIA_SERVER_OPEN_WINDOW,
								MEDIA_SERVER_CLOSE_WINDOW,
							};





//this is self explainatory.====================================================
enum MediaServerExit_Type {		MEDIA_SERVER_NORMAL_OPERATION 						= 0,
								MEDIA_SERVER_FAILED_TO_INITIALIZE_AUDIO_HARDWARE	= 1,
								MEDIA_SERVER_UNDEFINED_ERROR						= 2,
								MEDIA_SERVER_NO_AUDIO_HARDWARE						= 3};



#endif