#!/bin/sh
# This just removes all object files, archives, and executables
# generable by running "jam" this directory.
rm source/lib/*.o
rm source/lib/*.so
rm cppunit/cppunit.a
rm cppunit/src/*.o
rm test/Test.StorageKit.OpenBeOS
rm test/Test.StorageKit.R5
rm test/*.o

