#!/bin/sh
# Shell script to compile stuff until we get
# around to using Jam like we're supposed to

echo
echo ----------------------------------------------------------------------
echo Compiling StorageKit.Error and Test.Error.cpp
echo ----------------------------------------------------------------------
gcc Test.Error.cpp Error.cpp

echo
echo ----------------------------------------------------------------------
echo Compiling Path.cpp
echo ----------------------------------------------------------------------
gcc -c Path.cpp

echo
echo ----------------------------------------------------------------------
echo Compiling kernel_interface.POSIX.cpp
echo ----------------------------------------------------------------------
gcc -c kernel_interface.POSIX.cpp


echo
