#ifndef GLOBAL_SERVER_CLIENT_ID
#define GLOBAL_SERVER_CLIENT_ID

#define EVENT_WINDOW_IS_DYING 			0
#define EVENT_NODE_CREATED 				1
#define EVENT_NODE_DELETED 				2
#define EVENT_CONNECTION_MADE			3
#define EVENT_CONNECTION_BROKEN			4
#define EVENT_BUFFER_CREATED			5
#define EVENT_BUFFER_DELETED			6
#define EVENT_TRANSPORT_STATE			7
#define EVENT_PARAMETER_CHANGED			8
#define EVENT_FORMAT_CHANGED			9
#define EVENT_WEB_CHANGED				10	
#define EVENT_DEFAULT_CHANGED			11
#define EVENT_NEW_PARAMETER				12
#define EVENT_NODE_STOPPED				13
#define EVENT_FLAVORS_CHANGED			14
#define EVENT_APP_REGISTERED			15
#define EVENT_APP_UNREGISTERED			16
#define EVENT_SERVER_STARTED			17
#define EVENT_SERVER_DYING				18
#define EVENT_SERVER_DEATH_REQUESTED 	19
#define EVENT_DEVICE_CHANGED			20
#define EVENT_UPDATE_DEVICE_LIST 		21


#endif